"""Reading geometry node trees at a size a language model can afford.

A node graph is not hard to recover - nothing was destroyed when it was saved.
It is hard to *read*: it is a 2D graph with 7% of its nodes carrying a custom
label, and any linear serialisation of it is long. Measured on this repo's
reference scene, one 72-node tree costs ~6.4k tokens as JSON and ~18.6k tokens
as NodeToPython script, of which ~85% is boilerplate property assignment.

So this module does not serialise. It reports the structure a human already
reads off the canvas - which frames exist, what is in them, what the group's
interface is - and leaves the node-by-node detail to be fetched one frame at a
time. Frames are the point: they are the only human-authored names in a typical
tree, so they are the closest thing the format has to function names.

Faithful round-tripping is NodeToPython's job, not this module's. The two are
different tools because a faithful representation and a cheap one are different
things.
"""

import bpy

# Node types that carry no operation - they exist to organise the canvas. They
# are counted separately rather than listed, because a reroute tells the reader
# nothing about what a frame computes.
STRUCTURAL = {"NodeFrame", "NodeReroute"}

# Properties that describe where a node sits or how it is drawn, never what it
# computes. They are dropped from a detail read: canvas position is the part a
# human reads and a reader of this format does not, and reporting it costs more
# than everything else on a plain node put together. `mute` is deliberately not
# here - a muted node changes the result, so that is semantics, not decoration.
#
# This list was originally built from what showed up in practice, which misses
# anything the reference scene happens not to use. Checked since against
# rna_nodetree.cc: `dimensions` and the bl_* introspection properties are all
# read-only and already filtered, but `active_index` and `color_tag` are
# writable and had to be named here.
COSMETIC_PROPS = frozenset({
    "name", "label", "location", "location_absolute", "width", "height",
    "width_hidden", "parent", "select", "hide", "show_options", "show_preview",
    "show_texture", "color", "use_custom_color", "warning_propagation",
    # Which row is highlighted in a zone's item list - "Index of the active
    # item", UI selection state in exactly the way `select` is. It reads as
    # meaningful ("why is this one 1?") while recording only that someone
    # clicked the second row once, which is worse than costing tokens.
    "active_index",
    # The node header colour tag. Decoration, and unlike `label` it carries no
    # author intent that a reader could use.
    "color_tag",
})

# Zone input nodes, paired with an output node of the matching type. Kept as a
# mapping rather than derived from bl_idname because an unpaired zone is a
# broken tree and we want to name the pair we expected to find.
ZONE_PAIRS = {
    "GeometryNodeSimulationInput": "GeometryNodeSimulationOutput",
    "GeometryNodeRepeatInput": "GeometryNodeRepeatOutput",
    "GeometryNodeForeachGeometryElementInput":
        "GeometryNodeForeachGeometryElementOutput",
}


def _type_counts(nodes):
    """{bl_idname: count} for `nodes`, most common first.

    Counts rather than a list: a frame holding twelve Math nodes is described
    by "12 ShaderNodeMath", and naming Math.001 through Math.012 individually
    adds length without adding information.
    """
    counts = {}
    for node in nodes:
        counts[node.bl_idname] = counts.get(node.bl_idname, 0) + 1
    return dict(sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])))


def _labelled(node):
    """The most informative name for `node`, or None if it has none.

    node.name is autogenerated ("Math.001") and says nothing, so it is not a
    fallback here - reporting it would dilute the labels that are real.
    """
    return node.label or None


def tree_users(tree):
    """Everything that would be affected by rebuilding `tree`.

    Both halves matter for safety. Objects hold their per-modifier input values
    keyed by *interface socket identifier*, and those identifiers are reissued
    on rebuild (Socket_0 becomes Socket_2), so regenerating a group's interface
    silently resets every user's settings. Other node groups matter because a
    Group node referencing this tree breaks the same way.
    """
    objects, modifiers = [], []
    for obj in bpy.data.objects:
        for mod in obj.modifiers:
            if getattr(mod, "node_group", None) == tree:
                modifiers.append((obj.name, mod.name))
                if obj.name not in objects:
                    objects.append(obj.name)

    groups = []
    for group in bpy.data.node_groups:
        if group == tree:
            continue
        if any(getattr(n, "node_tree", None) == tree for n in group.nodes):
            groups.append(group.name)

    # Objects and modifiers are counted separately because they answer
    # different questions, and the smaller number is the misleading one. Input
    # values are stored per *modifier*, so a group on 14 objects can still have
    # 17 sets of values to lose - an object may carry the same group twice.
    return {"objects": objects, "node_groups": groups,
            "modifier_count": len(modifiers),
            "total": len(objects) + len(groups)}


def tree_interface(tree):
    """The group's public interface, flattened, with panel membership.

    The identifier is included on purpose and is the most important field here:
    it is the key an object's modifier stores its value under, it is not
    derivable from the name, and it is not stable across a rebuild. Anything
    that edits an interface needs to see it.
    """
    items = []
    for item in tree.interface.items_tree:
        if item.item_type == "PANEL":
            items.append({"kind": "panel", "name": item.name})
            continue
        entry = {
            "kind": "socket",
            "name": item.name,
            "identifier": item.identifier,
            "in_out": item.in_out,
            "socket_type": item.socket_type,
        }
        parent = getattr(item, "parent", None)
        # The root panel has no name and is not a panel the user made; only
        # report membership when the socket really sits inside one.
        if parent is not None and getattr(parent, "name", ""):
            entry["panel"] = parent.name
        if item.description:
            entry["description"] = item.description
        items.append(entry)
    return items


def tree_zones(tree):
    """Zone pairs in `tree`, each flagged with whether it is actually paired.

    An input node whose paired_output is None is a broken zone. Blender shows
    this as an error on the canvas but exposes no error attribute on the node,
    so a script that built the zone wrongly reports success unless something
    checks pairing explicitly.
    """
    zones = []
    for node in tree.nodes:
        expected = ZONE_PAIRS.get(node.bl_idname)
        if expected is None:
            continue
        output = getattr(node, "paired_output", None)
        zones.append({
            "type": node.bl_idname,
            "input": node.name,
            "output": output.name if output else None,
            "paired": output is not None,
        })
    return zones


def _frame_entry(tree, frame):
    """Summarise one frame: its label, and what is inside it.

    Children are found by walking every node's parent rather than by asking the
    frame, because a frame holds no child list - parent is a one-way pointer.

    Compared with == and never with `is`. Blender hands out a fresh Python
    wrapper each time a node reference is read, so `node.parent is frame` is
    False even when they are the same node; == compares the underlying data.
    The first version of this used `is` and every frame reported zero children
    while the tree plainly had 32 - wrong, and silently so.
    """
    children = [n for n in tree.nodes if n.parent == frame]
    active = [n for n in children if n.bl_idname not in STRUCTURAL]
    entry = {
        "label": frame.label or None,
        "name": frame.name,
        "nodes": len(active),
        "types": _type_counts(active),
    }
    labels = [_labelled(n) for n in active]
    labels = [x for x in labels if x]
    if labels:
        entry["labelled_nodes"] = labels
    nested = [n.name for n in children if n.bl_idname == "NodeFrame"]
    if nested:
        entry["nested_frames"] = nested
    return entry


def tree_outline(tree):
    """A structural summary of `tree`, sized for reading rather than rebuilding.

    Everything here is cheap and non-destructive; nothing in this function
    touches the tree. The detail deliberately stops at "what is in each frame" -
    fetching the nodes and links of one frame is a separate, targeted call, and
    that two-step read is the whole reason this exists.
    """
    if tree.bl_idname != "GeometryNodeTree":
        raise TypeError(
            f"{tree.name!r} is a {tree.bl_idname}, not a GeometryNodeTree")

    frames = [n for n in tree.nodes if n.bl_idname == "NodeFrame"]
    active = [n for n in tree.nodes if n.bl_idname not in STRUCTURAL]
    unframed = [n for n in active if n.parent is None]

    outline = {
        "name": tree.name,
        "counts": {
            "nodes": len(active),
            "links": len(tree.links),
            "frames": len(frames),
            "reroutes": sum(1 for n in tree.nodes
                            if n.bl_idname == "NodeReroute"),
        },
        "users": tree_users(tree),
        "interface": tree_interface(tree),
        "frames": [_frame_entry(tree, f) for f in frames],
        "unframed": {"nodes": len(unframed), "types": _type_counts(unframed)},
    }

    zones = tree_zones(tree)
    if zones:
        outline["zones"] = zones

    # Nested groups are a dependency list: reading this tree usually means
    # reading them too, and restoring it means restoring them first.
    deps = {}
    for node in tree.nodes:
        sub = getattr(node, "node_tree", None)
        if sub is not None:
            deps[sub.name] = deps.get(sub.name, 0) + 1
    if deps:
        outline["group_dependencies"] = deps

    # Labels are how a tree becomes readable, so report how much of that work
    # has been done. A low ratio is the signal that annotation is worth doing.
    labelled = sum(1 for n in active if n.label)
    outline["annotation"] = {
        "labelled_nodes": labelled,
        "framed_nodes": len(active) - len(unframed),
        "total_nodes": len(active),
    }
    return outline


def _jsonable(value, _depth=0):
    """A socket value as JSON, or None if it has no useful scalar form.

    Floats are rounded hard on purpose: a socket sitting at 0.5 serialises as
    0.5000000074505806 otherwise, which is three times the length and none of
    the meaning.
    """
    if isinstance(value, bool) or isinstance(value, int) or value is None:
        return value
    if isinstance(value, float):
        return round(value, 4)
    if isinstance(value, str):
        return value
    if isinstance(value, bpy.types.ID):
        return value.name
    if _depth == 0 and hasattr(value, "__len__"):
        try:
            return [_jsonable(v, _depth + 1) for v in value]
        except TypeError:
            return None
    return None


def socket_ref(node, socket, is_output):
    """A name for `socket` that identifies it uniquely within its node.

    Socket names are not unique: a Math node has three sockets called "Value",
    two in and one out. Referring to them by name alone makes "A.Value ->
    B.Value" ambiguous, and for a SUBTRACT or DIVIDE node the operand order is
    the whole meaning - so a plain-name reference does not merely lose detail,
    it describes a graph that cannot be rebuilt. Disambiguate with the index,
    and only when it is actually needed, since most sockets are unique.
    """
    sockets = node.outputs if is_output else node.inputs
    index = next((i for i, s in enumerate(sockets) if s == socket), None)
    if index is None:
        return socket.name
    name = socket.name or socket.identifier
    if sum(1 for s in sockets if (s.name or s.identifier) == name) > 1:
        return f"{name}[{index}]"
    return name


class _Defaults:
    """Property and socket values a node type has when freshly created.

    Reporting every property of every node buries the few that were set: a Math
    node carries `use_clamp` whether or not anyone touched it. Blender exposes
    no "is this at its default" flag, so the only reliable comparison is
    against a new node of the same type. One throwaway node per type is made in
    a scratch tree, which must be removed again - see close().

    The obvious cheaper alternative is RNA's own `prop.default`, which needs no
    scratch datablock at all. It does not work, and quietly:

      - It disagrees with reality. A fresh FunctionNodeCompare has
        operation='GREATER_THAN' while `prop.default` reports 'EQUAL', because
        the node's init() runs after RNA defaults. Trusting it would report an
        untouched Compare node as deliberately set on every read.
      - It cannot see sockets at all. A Math node's inputs default to 0.5, and
        that lives on the socket, not among the node's RNA properties. Half of
        what this class caches would simply be missing.

    So the scratch tree is the price of a diff that is actually correct.
    """

    def __init__(self):
        self._tree = bpy.data.node_groups.new(
            "__mcp_defaults__", "GeometryNodeTree")
        self._cache = {}

    def get(self, bl_idname):
        if bl_idname not in self._cache:
            props, inputs = {}, {}
            try:
                node = self._tree.nodes.new(bl_idname)
            except (RuntimeError, TypeError):
                # A type that cannot be instantiated bare (or was removed in
                # this Blender version) just means no elision for that node.
                self._cache[bl_idname] = (props, inputs)
                return self._cache[bl_idname]
            try:
                for prop in node.bl_rna.properties:
                    if prop.identifier == "rna_type" or prop.is_readonly:
                        continue
                    props[prop.identifier] = _jsonable(
                        getattr(node, prop.identifier, None))
                for i, socket in enumerate(node.inputs):
                    if hasattr(socket, "default_value"):
                        inputs[i] = _jsonable(socket.default_value)
            finally:
                self._tree.nodes.remove(node)
            self._cache[bl_idname] = (props, inputs)
        return self._cache[bl_idname]

    def close(self):
        if self._tree is not None:
            bpy.data.node_groups.remove(self._tree)
            self._tree = None


def _node_detail(node, defaults):
    """One node: what it is, what it is called, and what was changed on it.

    Only unlinked inputs are reported. A linked socket's default_value is dead
    data - the link overrides it - so including it would describe the node
    wrongly as well as at length.
    """
    entry = {"name": node.name, "type": node.bl_idname}
    if node.label:
        entry["label"] = node.label

    default_props, default_inputs = defaults.get(node.bl_idname)

    # What is left after eliding defaults is exactly the settings someone
    # chose: Math.operation = SUBTRACT survives, use_clamp = False does not.
    settings = {}
    for prop in node.bl_rna.properties:
        if prop.identifier == "rna_type" or prop.identifier in COSMETIC_PROPS:
            continue
        if prop.is_readonly:
            continue
        value = _jsonable(getattr(node, prop.identifier, None))
        if value is None or value == "":
            continue
        if prop.identifier in default_props and \
                default_props[prop.identifier] == value:
            continue
        settings[prop.identifier] = value
    if settings:
        entry["settings"] = settings

    inputs = {}
    for i, socket in enumerate(node.inputs):
        if socket.is_linked or not hasattr(socket, "default_value"):
            continue
        value = _jsonable(socket.default_value)
        if value is None:
            continue
        if i in default_inputs and default_inputs[i] == value:
            continue
        inputs[socket_ref(node, socket, is_output=False)] = value
    if inputs:
        entry["inputs"] = inputs
    return entry


def node_detail(tree, frame=None):
    """The nodes of one frame, with the links among and around them.

    `frame` names a frame by label or by node name; None selects the nodes that
    sit outside every frame. Both are needed - half the trees in the reference
    scene have no frames at all, so a frame-only drill-down would have no way
    into them.

    Boundary links are reported separately from internal ones because they are
    what makes a frame readable in isolation: they are its inputs and outputs.
    """
    if tree.bl_idname != "GeometryNodeTree":
        raise TypeError(
            f"{tree.name!r} is a {tree.bl_idname}, not a GeometryNodeTree")

    if frame is None:
        selected = [n for n in tree.nodes
                    if n.parent is None and n.bl_idname not in STRUCTURAL]
        title = None
    else:
        match = next((f for f in tree.nodes if f.bl_idname == "NodeFrame"
                      and frame in (f.label, f.name)), None)
        if match is None:
            known = [f.label or f.name for f in tree.nodes
                     if f.bl_idname == "NodeFrame"]
            raise ValueError(
                f"No frame {frame!r} in {tree.name!r}. Frames here: {known}")
        selected = [n for n in tree.nodes
                    if n.parent == match and n.bl_idname not in STRUCTURAL]
        title = match.label or match.name

    names = {n.name for n in selected}
    internal, boundary = [], []
    for link in tree.links:
        src, dst = link.from_node, link.to_node
        if src is None or dst is None:
            continue
        inside_src, inside_dst = src.name in names, dst.name in names
        if not (inside_src or inside_dst):
            continue
        edge = {
            "from": f"{src.name}.{socket_ref(src, link.from_socket, True)}",
            "to": f"{dst.name}.{socket_ref(dst, link.to_socket, False)}",
        }
        # An invalid link is Blender's only machine-readable "this is broken"
        # signal on a node tree, so never drop it silently.
        if not link.is_valid:
            edge["invalid"] = True
        (internal if inside_src and inside_dst else boundary).append(edge)

    defaults = _Defaults()
    try:
        nodes = [_node_detail(n, defaults) for n in selected]
    finally:
        # The scratch tree is a real datablock in the user's file until this
        # runs, so it is removed even if a node blows up mid-read.
        defaults.close()

    return {
        "tree": tree.name,
        "frame": title,
        "nodes": nodes,
        "links": internal,
        "boundary_links": boundary,
    }


def _evaluate_users(tree, max_objects):
    """Evaluate each object using `tree` and collect what Blender complains about.

    This is the only check here that can catch a tree which is structurally
    perfect and still wrong. Blender reports node problems on the *modifier*,
    not on the node or the tree - which is why they are easy to miss from
    script - and the list only fills once the depsgraph has actually run, so
    the evaluated mesh is pulled deliberately rather than as a side effect.

    Output geometry counts are reported alongside because the loudest failure
    in geometry nodes is silent: a tree that evaluates cleanly and emits
    nothing raises no warning at all, and zero vertices is the only evidence.
    """
    results = []
    depsgraph = bpy.context.evaluated_depsgraph_get()
    depsgraph.update()

    for obj in bpy.data.objects:
        if len(results) >= max_objects:
            break
        for mod in obj.modifiers:
            if getattr(mod, "node_group", None) != tree:
                continue
            entry = {"object": obj.name, "modifier": mod.name,
                     "warnings": [{"type": w.type, "message": w.message}
                                  for w in mod.node_warnings]}
            try:
                evaluated = obj.evaluated_get(depsgraph)
                mesh = evaluated.to_mesh()
                if mesh is None:
                    entry["output"] = None
                else:
                    entry["output"] = {
                        "vertices": len(mesh.vertices),
                        "edges": len(mesh.edges),
                        "faces": len(mesh.polygons),
                    }
                evaluated.to_mesh_clear()
            except (RuntimeError, AttributeError) as exc:
                # Plenty of object types cannot produce a mesh at all. That is
                # not a fault in the tree, so it is reported rather than raised.
                entry["output"] = {"unavailable": str(exc)}
            results.append(entry)
            break
    return results


def validate_tree(tree, evaluate=True, max_objects=8):
    """Check a geometry node tree and report everything wrong with it.

    Written to be called after anything that writes to a tree. A script that
    builds a graph reports success as long as it did not raise, which says
    nothing about whether the graph it built works - so this is the other half
    of every write, not an optional extra.
    """
    if tree.bl_idname != "GeometryNodeTree":
        raise TypeError(
            f"{tree.name!r} is a {tree.bl_idname}, not a GeometryNodeTree")

    problems = []

    # An invalid link is Blender's only static "this is broken" flag on a node
    # tree. It survives in the file and shows as a red link on the canvas.
    for link in tree.links:
        if link.is_valid:
            continue
        src, dst = link.from_node, link.to_node
        if src is None or dst is None:
            problems.append({"kind": "dangling_link", "detail": "link has no endpoint"})
            continue
        problems.append({
            "kind": "invalid_link",
            "detail": f"{src.name}.{socket_ref(src, link.from_socket, True)} -> "
                      f"{dst.name}.{socket_ref(dst, link.to_socket, False)}",
        })

    for zone in tree_zones(tree):
        if not zone["paired"]:
            problems.append({
                "kind": "unpaired_zone",
                "detail": f"{zone['input']} ({zone['type']}) has no paired "
                          f"output - the zone is incomplete",
            })

    # A group that produces nothing is usually a half-finished edit rather than
    # a design choice, and it is invisible on the canvas.
    outputs = [n for n in tree.nodes if n.bl_idname == "NodeGroupOutput"]
    if not outputs:
        problems.append({"kind": "no_group_output",
                         "detail": "tree has no Group Output node"})
    elif not any(s.is_linked for n in outputs for s in n.inputs):
        problems.append({"kind": "group_output_unconnected",
                         "detail": "nothing is linked into Group Output"})

    users = tree_users(tree)

    evaluated = None
    truncated = None
    if evaluate and users["modifier_count"]:
        evaluated = _evaluate_users(tree, max_objects)
        for entry in evaluated:
            for warning in entry["warnings"]:
                if warning["type"] == "ERROR":
                    problems.append({
                        "kind": "node_error",
                        "detail": f"{entry['object']}: {warning['message']}",
                    })
            output = entry.get("output") or {}
            if output.get("vertices") == 0 and output.get("faces") == 0:
                problems.append({
                    "kind": "empty_output",
                    "detail": f"{entry['object']}: evaluates to no geometry",
                })
        if users["modifier_count"] > len(evaluated):
            truncated = (
                f"evaluated {len(evaluated)} of {users['modifier_count']} "
                f"modifiers; raise max_objects for the rest")

    # Assembled once, after every check has run. An earlier version built the
    # report first and kept appending to the same list object afterwards. That
    # worked, but only through aliasing: `ok` and `problems` were correct
    # because they happened to refer to a list still being mutated. It is the
    # kind of thing a later tidy-up breaks silently, so the order is explicit.
    report = {
        "tree": tree.name,
        "users": users,
        "problems": problems,
        "ok": not problems,
    }
    if evaluated is not None:
        report["evaluation"] = evaluated
    if truncated is not None:
        report["evaluation_truncated"] = truncated
    return report


def annotate_tree(tree, labels=None, frames=None, undo_push=True):
    """Write labels and frames onto a tree - the one edit that cannot break it.

    Labels and frames have no effect on evaluation, so this is the only write
    in this module that is safe on a group with users. That is what makes it
    worth having as its own tool rather than a use of execute_code: annotating
    is the highest-value, lowest-risk thing that can be done to a node tree.

    It applies annotations rather than inventing them. Nothing here can know
    that Math.009 computes a time in seconds - that comes from reading the
    graph - so the caller supplies the meaning and this puts it where both a
    human and a later reader will find it.

    Every item is reported as applied or skipped. A rename that silently hit no
    node is the failure mode worth avoiding: autogenerated node names shift, so
    a stale name is likely rather than exotic.
    """
    if tree.bl_idname != "GeometryNodeTree":
        raise TypeError(
            f"{tree.name!r} is a {tree.bl_idname}, not a GeometryNodeTree")

    by_name = {n.name: n for n in tree.nodes}
    applied, skipped = [], []

    for node_name, label in (labels or {}).items():
        node = by_name.get(node_name)
        if node is None:
            skipped.append({"kind": "label", "target": node_name,
                            "reason": "no node with that name"})
            continue
        previous = node.label
        # None clears a label; anything else is set as text.
        node.label = "" if label is None else str(label)
        applied.append({"kind": "label", "target": node_name,
                        "from": previous or None, "to": node.label or None})

    for spec in (frames or []):
        frame_label = spec.get("label")
        members = spec.get("nodes") or []
        if not frame_label:
            skipped.append({"kind": "frame", "target": None,
                            "reason": "frame needs a label"})
            continue
        if not members:
            skipped.append({"kind": "frame", "target": frame_label,
                            "reason": "frame needs at least one node"})
            continue

        # Reuse a frame with the same label rather than stacking a second one
        # on top of it, so running the same annotation twice is not destructive.
        frame = next((n for n in tree.nodes if n.bl_idname == "NodeFrame"
                      and n.label == frame_label), None)
        created = frame is None
        if created:
            frame = tree.nodes.new("NodeFrame")
            frame.label = frame_label
            by_name[frame.name] = frame

        moved, missing = [], []
        for node_name in members:
            node = by_name.get(node_name)
            if node is None or node == frame:
                missing.append(node_name)
                continue
            node.parent = frame
            moved.append(node_name)

        if not moved and created:
            # An empty frame is clutter, so do not leave one behind.
            tree.nodes.remove(frame)
            skipped.append({"kind": "frame", "target": frame_label,
                            "reason": f"none of its nodes exist: {missing}"})
            continue

        entry = {"kind": "frame", "target": frame_label,
                 "created": created, "nodes": moved}
        if missing:
            entry["missing"] = missing
        applied.append(entry)

    if undo_push:
        # Without this the annotation is not a step the user can Ctrl-Z, which
        # for a write triggered from outside Blender is the least they should
        # get. The addon passes undo_push=False and pushes through its own undo
        # module instead, so that the step is counted and can be taken back by
        # the undo_edit tool; this branch is for calling annotate_tree directly.
        try:
            bpy.ops.ed.undo_push(message=f"MCP annotate {tree.name}")
        except (RuntimeError, AttributeError):
            pass

    active = [n for n in tree.nodes if n.bl_idname not in STRUCTURAL]
    return {
        "tree": tree.name,
        "applied": applied,
        "skipped": skipped,
        "annotation": {
            "labelled_nodes": sum(1 for n in active if n.label),
            "framed_nodes": sum(1 for n in active if n.parent is not None),
            "total_nodes": len(active),
        },
    }


def list_trees():
    """Every geometry node tree in the file, with just enough to choose one."""
    trees = []
    for tree in bpy.data.node_groups:
        if tree.bl_idname != "GeometryNodeTree":
            continue
        users = tree_users(tree)
        trees.append({
            "name": tree.name,
            "nodes": sum(1 for n in tree.nodes
                         if n.bl_idname not in STRUCTURAL),
            "links": len(tree.links),
            "frames": sum(1 for n in tree.nodes if n.bl_idname == "NodeFrame"),
            "users": users["total"],
        })
    return {"count": len(trees), "trees": trees}
